apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-hello-world
  template:
    metadata:
      labels:
        app: backend-hello-world
    spec:
      containers:
      - name: backend-hello-world
        image: repositoryassessment.azurecr.io/repositoryassessment:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
# ClusterIP for internal communication only
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend-hello-world
  ports:
  - name: http
    port: 8080