apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: backend:04.05.2024
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
# ClusterIP for internal communication only
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend-app
  ports:
  - name: http
    port: 8080